databases:
  - name: Villow
    databaseName: dpg-coevl60cmk4c73fta630-a
    user: villow_g3v0_user

services:
  - type: web
    name: Villow
    runtime: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    plan: free
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: dpg-coevl60cmk4c73fta630-a
          property: "postgres://villow_g3v0_user:ceoYx8oIY73o9V1Buez0ebgXR2pR7Ukx@dpg-coevl60cmk4c73fta630-a/villow_g3v0"
      - key: RAILS_MASTER_KEY
        sync: false
